version: '3'
services:
  ethservice:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      DATABASE_DIALECT: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ethService0114
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      CONTEXT_TIMEOUT_SECS: 10
      GIN_MODE: debug
    restart: 'always'
    depends_on:
      - 'db'
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    command:
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_connections=yes"
      - "-c"
      - "log_disconnections=yes"
      - "-c"
      - "log_statement=all"
    volumes:
      - ./db_seed.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ethService0114
    restart: always