version: '3'
services:
  ethservice:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      DATABASE_DIALECT: postgres
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: ethService0114
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
    restart: 'always'
    depends_on:
      - 'db'
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    command:
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_connections=yes"
      - "-c"
      - "log_disconnections=yes"
      - "-c"
      - "log_statement=all"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=ethService0114
    restart: always